### ISSUE TITLE
Failed to activate the flow-ide package

### ISSUE THREAD

**Issue by ali-master** [steelbrain/flow-ide#102]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [flow-ide](https://github.com/steelbrain/flow-ide) package 1.5.0

### Stack Trace

Failed to activate the flow-ide package

```
At Package not initialized

Error: Package not initialized
  at /packages/nuclide/modules/nuclide-commons-atom/createPackage.js:48:15)
  at Provider.module.exports.Provider.provide (<embedded>:115569:58)
  at ServiceHub.module.exports.ServiceHub.provide (<embedded>:68815:26)
  at Package.module.exports.Package.activateServices (<embedded>:69312:77)
  at Package.module.exports.Package.activateNow (<embedded>:69122:22)
  at <embedded>:69091:38
  at Package.module.exports.Package.measure (<embedded>:68965:21)
  at <embedded>:69084:32
  at Package.module.exports.Package.activate (<embedded>:69081:40)
  at PackageManager.module.exports.PackageManager.activatePackage (<embedded>:20537:40)
  at <embedded>:53409:35
  at exit (<embedded>:53018:22)
  at triggerExitCallback (<embedded>:115985:17)
  at ChildProcess.<anonymous> (<embedded>:116015:17)
  at emitTwo (events.js:106:13)
  at ChildProcess.emit (events.js:191:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

```

### Commands

```
     -3:40.6.0 settings-view:open (input.hidden-input)
     -3:36.1.0 core:backspace (input.hidden-input)
     -1:25.9.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.3 
auto-detect-indentation 1.3.0 
auto-indent 0.5.0 
autocomplete-modules 1.6.10 
duotone-dark-earth-syntax 2.1.0 
duotone-dark-forest-syntax 2.1.0 
duotone-dark-sea-syntax 2.1.0 
duotone-dark-space-syntax 2.1.0 
duotone-dark-syntax 2.1.0 
duotone-light-syntax 2.1.0 
editor-stats 0.17.0 
editorconfig 2.2.2 
emmet 2.4.3 
emmet-jsx-css-modules 1.0.0 
file-icons 2.1.8 
firewatch-syntax 1.1.1 
flow-ide 1.5.0 
git-plus 7.9.3 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
hyperclick 0.1.1 
language-babel 2.66.0 
language-graphql 0.9.0 
language-ini 1.19.0 
language-javascript-jsx 0.3.7 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-postcss 1.3.1 
language-rust 0.4.11 
language-swift 0.5.0 
language-thrift 1.0.2 
linter 2.2.0 
MagicPython 1.0.10 
merge-conflicts 1.4.5 
minimap 4.28.2 
nuclide 0.236.0 
nuclide-format-js 0.0.36 
nuclide-test-runner-jest 0.3.0 
pristine-ui 1.0.15 
react-native-snippets 0.3.0 
regex-railroad-diagram 0.19.3 
set-syntax 0.3.2 
sort-lines 0.14.0 
tool-bar 1.1.0 
tree-view-git-branch 0.1.2 
tree-view-git-status 1.4.0 
tree-view-open-files 0.3.0 
wakatime 7.0.3 
```

**Comment by steelbrain** [comment]
Issue is coming from Nuclide not flow-ide. Thanks!
