### ISSUE TITLE
[Linter] Error running RuboCop

### ISSUE THREAD

**Issue by bcorner13** [steelbrain/flow-ide#136]
[Linter] Error running RuboCop Error: /opt/chefdk/embedded/lib/ruby/site_ruby/2.4.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem rubocop (>= 0.a) with executable rubocop (Gem::GemNotFoundException)
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.4.0/rubygems.rb:308:in `activate_bin_path'
	from /opt/chefdk/embedded/bin/rubocop:23:in `<main>'
    at ChildProcess.<anonymous> (/Users/bcorner/.atom/packages/flow-ide/node_modules/sb-exec/lib/index.js:56)
    at emitTwo (events.js:106)
    at ChildProcess.emit (events.js:194)
    at maybeClose (internal/child_process.js:899)
    at Socket.<anonymous> (internal/child_process.js:342)
    at emitOne (events.js:96)
    at Socket.emit (events.js:191)
    at Pipe._handle.close [as _onclose] (net.js:510)

**Comment by lloiser** [comment]
This error is not related to `flow-ide`. You probably have a plugin for ruby installed (maybe https://atom.io/packages/linter-rubocop). Please open an issue there.
